#!/usr/bin/env python
# -*- coding: utf-8 -*-
import re
import sys

import htgettoken as ht
def log(*args, **kwargs):
    print(" ".join(map(str,args)), file=sys.stdout, flush=True, **kwargs)
ht.log = log

from htgettoken import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
