#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Copyright (c) 2025 Regents of the University of Minnesota
Author: Alex Wagner <wagn0033@umn.edu>, Dept. of Physics and Astronomy

Default Label Configuration

DO NOT EDIT THIS FILE!
This file is automatically generated. It may be overwritten by the 
DUNE HWDB Python utility at any time.

You may add or modify label settings by editing custom_config.py. The 
contents of that file and this file will be merged, with settings in the
custom configuration file overriding those in this file. (A node may
be set to None to effectively remove it.)
"""

contents = \
{
    "page sizes": {
        "A4": {
            "units": "mm",
            "size": (210.00, 297.00)
        },
        "Letter": {
            "units": "inch",
            "size": (8.500, 11.000)
        }
    },
    "label templates": {
        "A4-4x11-Generic": {
            "description": "A4 (210×297 mm), 51.5×26.6 mm labels, 44 per sheet",
            "page size": "A4",
            "label size": (51.50, 26.60),
            "horizontal offsets": (
                  2.00, 53.50, 105.00, 156.50
            ),
            "vertical offsets": (
                  2.20,  28.80,  55.40,  82.00,
                108.60, 135.20, 161.80, 188.40,
                215.00, 241.60, 268.02
            ),
            "rounding": 2.00
        },
        "A4-3x4-Generic": {
            "description": '''A4 (210×297 mm), 67×72 mm labels, 12 per sheet''',
            "page size": "A4",
            "label size": (67, 72),
            "horizontal offsets": (3.0, 72.0, 141.0),
            "vertical offsets": (2.5, 75.5, 148.5, 221.5),
            "rounding": 2.00,
        },
        "A4-6x11-Herma": {
            "description": "A4 (210×297 mm), 25.4×25.4 mm labels, 66 per sheet",
            "page size": "A4",
            "label size": (25.4, 25.4),
            "horizontal offsets": (16.1, 46.58, 77.06, 107.54, 138.02, 168.5),
            "vertical offsets": (
                       11.3,  36.7,  62.1,  87.5, 112.9, 
                      138.3, 163.7, 189.1, 214.5, 239.9,
                      265.3
            ),
            "rounding": 2.0,
        },

        "Letter-2x2-Avery":
        {
            "description": '''Letter (8.5”×11”), 5”×3.5” labels, 4 per sheet''',
            "page size": "Letter",
            "label size": (3.5, 5.0),
            "horizontal offsets": (0.5, 4.5),
            "vertical offsets": (0.5, 5.5),
            "rounding": 0.125,
        },
        "Letter-2x3-Avery": {
            "description": "Letter (8.5”×11”), 4”×3.333” labels, 6 per sheet",
            "page size": "Letter",
            "label size": (4.00, 3.333),
            "horizontal offsets": (0.156, 4.344),
            "vertical offsets": (0.500, 3.833, 7.167),
            "rounding": 0.125
        },
        "Letter-2x4-Avery":
        {
            "description": '''Letter (8.5”×11”), 4”×2.5” labels, 8 per sheet''',
            "page size": "Letter",
            "label size": (4.0, 2.5),
            "horizontal offsets": (0.156, 4.344),
            "vertical offsets": (0.5, 3.0, 5.5, 8.0),
            "rounding": 0.125,
        },
        "Letter-2x5-Avery":
        {
            "description": '''Letter (8.5”×11”), 4”×2” labels, 10 per sheet''',
            "units": "inch",
            "page size": "Letter",
            "label size": (4.0, 2.0),
            "horizontal offsets": (0.156, 4.344),
            "vertical offsets": (0.5, 2.5, 4.5, 6.5, 8.5),
            "rounding": 0.125,
        },
        "Letter-2x6-Avery":
        {
            "description": '''Letter (8.5”×11”), 4”×1.5” labels, 12 per sheet''',
            "page size": "Letter",
            "label size": (4.0, 1.5),
            "horizontal offsets": (0.156, 4.344),
            "vertical offsets": (1.0, 2.5, 4.0, 5.5, 7.0, 8.5),
            "rounding": 0.125,
        },
        "Letter-2x7-Avery":
        {
            "description": '''Letter (8.5”×11”), 4”×1.333” labels, 14 per sheet''',
            "page size": "Letter",
            "label size": (4.0, 1.33333),
            "horizontal offsets": (0.15625, 4.34375),
            "vertical offsets": (0.833, 2.167, 3.500, 4.833, 6.167, 7.500, 8.833),
            "rounding": 0.125,
        },
        "Letter-3x5-Avery":
        {
            "description": '''Letter (8.5”×11”), 2.625”×2” labels, 15 per sheet''',
            "page size": "Letter",
            "label size": (2.625, 2.0),
            "horizontal offsets": (0.156, 2.906, 5.656),
            "vertical offsets": (0.5, 2.5, 4.5, 6.5, 8.5),
            "rounding": 0.125,
        },
        "Letter-3x10-Avery":
        {
            "description": '''Letter (8.5”×11”), 2.625”×1” labels, 30 per sheet''',
            "page size": "Letter",
            "label size": (2.625, 1.0),
            "horizontal offsets": (0.156, 2.906, 5.656),
            "vertical offsets": (0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5),
            "rounding": 0.125,
        },
    },
    "layouts": {
        "QR-A4-3x4-Generic": {
            "label template": "A4-3x4-Generic",
            "orientation": "portrait",
            "debug": False,
            "elements": [
                {
                    "element type": "qr",
                    "alignment": "top-center",
                    "anchor": ["50%", "4%"],
                    "size": ["100%", "73%"],
                    "preserve aspect ratio": True,
                },
                {
                    "element type": "part id",
                    "alignment": "top-center",
                    "anchor": ["50%", "82%"],
                    "font size": "5%",
                },
                {
                    "element type": "part name",
                    "alignment": "top-center",
                    "anchor": ["50%", "90%"],
                    "font size": "5%",
                }
            ]
        },

        "QR-Letter-2x2-Avery":
        {
            "label template": "Letter-2x2-Avery",
            "elements": [
                {
                    "element type": "qr",
                    "alignment": "top-center",
                    "anchor": ["50%", "4%"],
                    "size": ["100%", "73%"],
                    "preserve aspect ratio": True,
                },
                {
                    "element type": "part id",
                    "alignment": "top-center",
                    "anchor": ["50%", "82%"],
                    "font size": "5%",
                },
                {
                    "element type": "part name",
                    "alignment": "top-center",
                    "anchor": ["50%", "90%"],
                    "font size": "5%",
                }
            ]
        },
        "QR-Letter-2x3-Avery": {
            "label template": "Letter-2x3-Avery",
            "orientation": "landscape",
            "debug": False,
            "elements": [
                {
                    "element type": "qr",
                    "alignment": "top-center",
                    "anchor": ["50%", "4%"],
                    "size": ["100%", "73%"],
                    "preserve aspect ratio": True,
                },
                {
                    "element type": "part id",
                    "alignment": "top-center",
                    "anchor": ["50%", "82%"],
                    "font size": "5%",
                },
                {
                    "element type": "part name",
                    "alignment": "top-center",
                    "anchor": ["50%", "90%"],
                    "font size": "5%",
                }
            ]
        },
        "QR-Letter-2x4-Avery": {
            "label template": "Letter-2x4-Avery",
            "orientation": "landscape",
            "debug": False,
            "elements": [
                {
                    "element type": "qr",
                    "alignment": "top-center",
                    "anchor": ["50%", "15%"],
                    "size": ["90%", "73%"],
                    "preserve aspect ratio": True,
                },
                {
                    "element type": "part id",
                    "alignment": "top-center",
                    "anchor": ["50%", "75%"],
                    "font size": "4%",
                },
                {
                    "element type": "part name",
                    "alignment": "top-center",
                    "anchor": ["50%", "83%"],
                    "font size": "4%",
                },
            ]
        },
        "QR-Letter-2x5-Avery": {
            "label template": "Letter-2x5-Avery",
            "orientation": "landscape",
            "debug": False,
            "elements": [
                {
                    "element type": "qr",
                    "alignment": "top-center",
                    "anchor": ["50%", "15%"],
                    "size": ["90%", "73%"],
                    "preserve aspect ratio": True,
                },
                {
                    "element type": "part id",
                    "alignment": "top-center",
                    "anchor": ["50%", "75%"],
                    "font size": "4%",
                },
                {
                    "element type": "part name",
                    "alignment": "top-center",
                    "anchor": ["50%", "83%"],
                    "font size": "4%",
                },
            ]
        },
        "QR-Letter-2x6-Avery": {
            "label template": "Letter-2x6-Avery",
            "orientation": "portrait",
            "debug": False,
            "elements": [
                {
                    "element type": "qr",
                    "alignment": "top-left",
                    "anchor": ["4%", "4%"],
                    "size": ["90%", "90%"],
                    "preserve aspect ratio": True,
                },
                {
                    "element type": "part id",
                    "alignment": "top-center",
                    "anchor": ["70%", "35%"],
                    "font size": "10%",
                },
                {
                    "element type": "part name",
                    "alignment": "top-center",
                    "anchor": ["70%", "53%"],
                    "font size": "10%",
                },
            ]
        },
        "QR-Letter-3x5-Avery": {
            "label template": "Letter-3x5-Avery",
            "orientation": "landscape",
            "debug": False,
            "elements": [
                {
                    "element type": "qr",
                    "alignment": "top-center",
                    "anchor": ["50%", "4%"],
                    "size": ["100%", "73%"],
                    "preserve aspect ratio": True,
                },
                {
                    "element type": "part id",
                    "alignment": "top-center",
                    "anchor": ["50%", "82%"],
                    "font size": "5%",
                },
                {
                    "element type": "part name",
                    "alignment": "top-center",
                    "anchor": ["50%", "90%"],
                    "font size": "5%",
                }
            ]
        },

        "Bar-Letter-2x7-Avery": {
            "label template": "Letter-2x7-Avery",
            "orientation": "portrait",
            "elements": [
                {
                    "element type": "bar",
                    "alignment": "top-center",
                    "anchor": ["50%", "10%"],
                    "size": ["90%", "55%"],
                    "preserve aspect ratio": False,
                },
                {
                    "element type": "external id",
                    "alignment": "top-center",
                    "anchor": ["50%", "68%"],
                    "font size": "10%",
                },
                {
                    "element type": "part name",
                    "alignment": "top-center",
                    "anchor": ["50%", "81%"],
                    "font size": "8%",
                    "font face": "Helvetica"
                },
            ]
        },
        "QR-A4-6x11-Herma_10107": {
            "label template": "A4-6x11-Herma",
            "orientation": "portrait", # or portrait
            "debug": False,
            "elements": [
                {
                    "element type": "qr",
                    "alignment": "top-center",
                    "anchor": ["50%", "4%"],
                    "size": ["75%", "75%"],
                    "preserve aspect ratio": True,
                },
                {
                    "element type": "part id",
                    "alignment": "top-center",
                    "anchor": ["50%", "83%"],
                    "font size": "5%",
                },
                {
                    "element type": "part name",
                    "alignment": "top-center",
                    "anchor": ["50%", "90%"],
                    "font size": "5%",
                },
            ]
        },
    },
    "label sets": {
        "default": [
            "QR-A4-3x4-Generic",
            "QR-A4-6x11-Herma_10107",
            "QR-Letter-2x4-Avery",
            "QR-Letter-3x5-Avery",
            "Bar-Letter-2x7-Avery",
        ],
    }
}
